services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "127.0.0.1:2181:2181"
    volumes: 
      - ./data/zoo/data:/var/lib/zookeeper/data
      - ./data/zoo/log:/var/lib/zookeeper/log
  
  kafka:
    image: confluentinc/cp-kafka:7.8.1
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes: 
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda:
    image: redpandadata/console:v2.8.2
    depends_on:
      - kafka
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper